# The local app (ADR-023) as a CPU-only image: the FastAPI app and the e5
# encoder on torch CPU. Generation stays outside, on the host's Ollama.
#
# No third-party text and no model weights enter this image. Only src/, ui/,
# tasks.py, requirements.txt, constraints.txt and the synthetic demo document
# under evals/app/ are copied, and .dockerignore keeps data/, runs/ and models/
# out of the build context as well. Uploaded documents live in /data/app, a
# host directory mounted at run time; the encoder downloads into the hf-cache
# volume on first use (docker-compose.yml).

# Pinned by digest, with the tag kept beside it: the tag is for a reader, the
# digest is what Docker resolves. `python:3.14-slim` is a moving target — it is
# rebuilt whenever a base package gets a CVE fix — so a rebuild of this file
# without the digest could quietly produce a different image from the one the
# tests ran against, which is the one property a container is supposed to have.
#
# This is an OCI image index, not a single-platform manifest, so linux/amd64 and
# linux/arm64 both still resolve from it. Pinning one platform's manifest digest
# would build on this machine and fail on an Apple Silicon one.
#
# Resolved 2026-09-19; holds Python 3.14.7; image built 2026-09-01.
# To move it, take the new digest and update the date and version above:
#   docker pull python:3.14-slim && docker inspect --format '{{index .RepoDigests 0}}' python:3.14-slim
# or, without Docker (what was used here — the daemon was not running):
#   T=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/python:pull" | python -c "import sys,json;print(json.load(sys.stdin)['token'])")
#   curl -sI -H "Authorization: Bearer $T" -H "Accept: application/vnd.oci.image.index.v1+json" \
#        https://registry-1.docker.io/v2/library/python/manifests/3.14-slim | grep -i docker-content-digest
FROM python:3.14-slim@sha256:cad9a2c871761c413caa6fdd6441c783451e740a48aaeba60ae62a8b53525ef6

# A build-time-only guard: if a RUN step ever tried to load a model (it must
# not — see the no-build-time-download check in tests/test_container_files.py),
# this stops it from reaching the network for one instead of failing loudly.
ARG HF_HUB_OFFLINE=1

# PYTHONUNBUFFERED: the startup banner and warnings reach `docker compose logs`
# as they are printed, not when a buffer fills.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    LEGALRAG_DATA_DIR=/data/app \
    HF_HOME=/home/app/.cache/huggingface

# A non-root user with a fixed uid, 1000, the usual first user on a Linux host,
# so what the app writes into the ./data/app bind mount belongs to that user.
# The directories the app writes are its own: a named volume takes the
# ownership of the directory it is mounted over.
RUN useradd --create-home --uid 1000 --shell /usr/sbin/nologin app \
 && mkdir -p /data/app /home/app/.cache/huggingface \
 && chown -R app:app /data/app /home/app/.cache

WORKDIR /app

# torch first, from the CPU wheel index: sentence-transformers in
# requirements.txt would otherwise pull the far larger CUDA build from PyPI.
# --no-deps: torch's own resolver must never reach anywhere but this index.
RUN pip install --no-cache-dir --no-deps --index-url https://download.pytorch.org/whl/cpu torch==2.14.0

# Then everything else, each package at its version in constraints.txt
# (generated by scripts/make_constraints.py). Its torch pin has no local label,
# so the CPU wheel above satisfies it and stays. Should a package still swap in
# a CUDA build of torch, the check after the install fails the build.
COPY requirements.txt constraints.txt ./
RUN pip install --no-cache-dir -c constraints.txt -r requirements.txt \
 && python -c "__import__('sys').exit(__import__('torch').version.cuda is not None)"

COPY src/ ./src/
COPY ui/ ./ui/
COPY tasks.py ./
# The synthetic demo document (evals/app/README.md), nothing else from evals/.
COPY evals/app/ ./evals/app/

USER app

EXPOSE 8000

# GET /, the chat page. Not /api/health: that asks Ollama twice on every call.
HEALTHCHECK --interval=30s --timeout=5s --start-period=30s --retries=3 \
    CMD ["python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/', timeout=4)"]

# 0.0.0.0: inside the container, 127.0.0.1 is the container's own loopback,
# which a published port cannot reach. The app prints a WARNING that the host
# is not a loopback address; that is expected here. It stays local all the
# same: docker-compose.yml publishes the port on the host's 127.0.0.1 only,
# and the Host allowlist still holds, since a browser on the host sends
# Host: 127.0.0.1:8000.
CMD ["python", "tasks.py", "app", "--host", "0.0.0.0", "--port", "8000"]
