"""Write constraints.txt: every package the image or CI can install, pinned.

    python scripts/make_constraints.py [--output PATH]

Offline. The roots are requirements.txt and requirements-ci.txt, `-r` includes
followed; each root's dependencies are walked through the installed
distributions' metadata (importlib.metadata), extras included. A dependency is
followed when its marker holds on Linux, where the image and CI install, or on
this machine. Each package is pinned to the version installed here without a
local label: `torch==2.14.0` still matches the CPU wheel `2.14.0+cpu`.

A package that is reachable but not installed here cannot be pinned: it is
listed on stderr and floats. An installed version outside a range something
requires is a conflict, also listed, and the exit code is then 1.
"""

from __future__ import annotations

import argparse
import importlib.metadata
import platform
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name
from packaging.version import Version

ROOT = Path(__file__).resolve().parents[1]
ROOTS = ("requirements.txt", "requirements-ci.txt")
INCLUDE = re.compile(r"^(?:-r|--requirement)[\s=]+(\S+)$")


@dataclass
class Closure:
    pins: dict[str, str] = field(default_factory=dict)  # distribution name -> version
    missing: list[str] = field(default_factory=list)  # reachable, not installed: unpinned
    conflicts: list[str] = field(default_factory=list)


def linux_environment() -> dict[str, str]:
    """Marker values where the image and CI install: Linux, this Python version."""
    return {**default_environment(), "os_name": "posix", "sys_platform": "linux", "platform_system": "Linux",
            "platform_machine": "x86_64", "platform_release": "", "platform_version": ""}


def read_requirements(path: Path) -> list[str]:
    """A requirements file's requirement strings, `-r` includes followed, options and comments dropped."""
    requirements: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = re.sub(r"(?:^|\s)#.*$", "", raw).strip()
        include = INCLUDE.match(line)
        if include:
            requirements += read_requirements(path.parent / include.group(1))
        elif line and not line.startswith("-"):
            requirements.append(line)
    return requirements


def closure(roots: list[str], environments: list[dict[str, str]],
            distribution=importlib.metadata.distribution) -> Closure:
    """Every installed distribution `roots` can pull in on any of `environments`."""
    result, missing, conflicts = Closure(), set(), set()
    extras_done: dict[str, set[str]] = {}
    queue = [(requirement, "a requirements file") for requirement in map(Requirement, roots)
             if _holds(requirement, {""}, environments)]
    while queue:
        requirement, parent = queue.pop()
        name = canonicalize_name(requirement.name)
        try:
            dist = distribution(requirement.name)
        except importlib.metadata.PackageNotFoundError:
            missing.add(name)
            continue
        dist_name, version = dist.metadata["Name"], Version(dist.version)
        if requirement.specifier and not requirement.specifier.contains(version, prereleases=True):
            conflicts.add(f"{dist_name} {dist.version} does not satisfy {requirement} (required by {parent})")
        new_extras = ({""} | set(requirement.extras)) - extras_done.get(name, set())
        if not new_extras:
            continue
        extras_done.setdefault(name, set()).update(new_extras)
        result.pins[dist_name] = version.public
        queue += [(dependency, dist_name) for dependency in map(Requirement, dist.requires or [])
                  if _holds(dependency, new_extras, environments)]
    result.missing, result.conflicts = sorted(missing), sorted(conflicts)
    return result


def _holds(requirement: Requirement, extras: set[str], environments: list[dict[str, str]]) -> bool:
    if requirement.marker is None:
        return "" in extras  # unconditional: followed once, not again for each new extra
    return any(requirement.marker.evaluate({**environment, "extra": extra})
               for environment in environments for extra in extras)


def render(pins: dict[str, str], header: str) -> str:
    lines = [f"{name}=={version}" for name, version in sorted(pins.items(), key=lambda item: canonicalize_name(item[0]))]
    return "\n".join([header, *lines]) + "\n"


def header() -> str:
    return "\n".join([
        "# Generated by `python scripts/make_constraints.py`; do not edit by hand.",
        "# Every package requirements.txt or requirements-ci.txt can pull in, extras",
        "# included, when its marker holds on Linux or on the machine that generated",
        f"# it (Python {platform.python_version()}, {sys.platform}), pinned to the version installed there",
        "# without a local label: torch==2.14.0 matches the CPU wheel 2.14.0+cpu.",
        "# The Dockerfile and CI install with `pip install -c constraints.txt ...`.",
        "# To change a pin: change a requirements file, install it, run the script.",
    ])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Write constraints.txt from the installed packages' metadata.")
    parser.add_argument("--output", type=Path, default=ROOT / "constraints.txt")
    args = parser.parse_args(argv)

    roots = [line for name in ROOTS for line in read_requirements(ROOT / name)]
    result = closure(roots, [linux_environment(), default_environment()])
    args.output.write_text(render(result.pins, header()), encoding="utf-8", newline="\n")
    print(f"{args.output.name}: {len(result.pins)} packages pinned")
    for name in result.missing:
        print(f"reachable but not installed here, so unpinned: {name}", file=sys.stderr)
    for conflict in result.conflicts:
        print(f"conflict: {conflict}", file=sys.stderr)
    return 1 if result.conflicts else 0


if __name__ == "__main__":
    raise SystemExit(main())
